config/routes.rb
Rails.application.routes.draw do
  resources :lists
end

app/models/list.rb
class List < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
      @lists = List.all
      render :index
    end

    def show
      @list = List.find(params[:id])
      render :show
    end

    def new
      @list = List.new
      render :new
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New List</h1>

<% if @list.errors.any? %>
  <h3>Oops there were some errors.Please try again:</h3>
  <ul>
    <% @List.errors.full_messages.each do |message| %>
      <li><%= message  %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h3><%= @list.name %></h3>

<h4><%= @list.description %></h4>

<p><%= link_to "return to lists", lists_path %></p>